name: 'setup-conda'
description: 'Provide a description here'
author: 'Sebastian Weigand'
inputs:
  python-version:
    description: 'input description here'
    default: 'default'

runs:
  using: 'node12'
  main: 'dist/index.js'
