name: "setup-conda"
description: "Provide a description here"
author: "Sebastian Weigand"
inputs:
  update-conda:
    description: "If conda should be updated before running other commands (default: 'false')"
    default: "false"
  python-version:
    description: "Python version which should be installed with conda (default: 'default')"
    default: "default"
  conda-channels:
    description: "Additional channels like 'conda-forge' which can be used to install packages"
    default: ""

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "code"
  color: "yellow"
