name: 'Test'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci
      - run: npm run build
      - name: Checking format
        run: npm run format-check
      - name: Linting code
        run: npm run lint
      - name: Running jest tests
        run: npm test

  test-integration-default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run release
      - uses: ./
      - run: conda --version
      - run: conda init bash
      - run: conda activate base
      - run: python --version
