name: 'Test'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci
      - run: npm run build
      - run: npm test
        with:
          conda-version: 'latest'
          python-version: 'default'

  test-integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: ./
      - run: conda --version
