name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci
      - run: npm run build
      - name: Checking format
        run: npm run format-check
      - name: Linting code
        run: npm run lint
      - name: Running jest tests
        run: npm test

  test-integration-default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Check initial python version
        run: python --version
      - name: install Dependencies
        run: npm ci
      - name: Build index.js
        run: npm run release
      - uses: ./
      - name: Check conda version
        run: conda --version
      - name: Check final python version
        run: |
          python --version
          python -c "import sys;print(sys.executable);print(sys.version_info)"

  test-integration-custom:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Check initial python version
        run: python --version
      - name: install Dependencies
        run: npm ci
      - name: Build index.js
        run: npm run release
      - uses: ./
        with:
          update-conda: true
          python-version: 3.6
          conda-channels: anaconda, conda-forge
      - name: Check conda version
        run: conda --version
      - name: Check final python version
        run: |
          python --version
          python -c "import sys;print(sys.executable);print(sys.version_info)"
